sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION=us-east-1
before_install: make clean
before_script:
  - export TEST="1"
  - export GIT_BRANCH=$TRAVIS_BRANCH
  - export GIT_COMMIT_SHA=$TRAVIS_COMMIT
script:
  - make test
#deploy:
#  provider: script
#  script: make deploy stage=prod
#  on:
#    branch: master
